workspace "Crown"
	architecture "x64"

	configurations
	{
		"Debug",
		"Release",
		"Dist"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

-- Include directories relative to root folder (solution directory)
IncludeDir = {}
IncludeDir["GLFW"] = "Crown/vendor/GLFW/include"
IncludeDir["Glad"] = "Crown/vendor/Glad/include"
IncludeDir["glm"] = "Crown/vendor/glm"
IncludeDir["ImGui"] = "Crown/vendor/imgui"
IncludeDir["stb"] = "Crown/vendor/stb"

include "Crown/vendor/GLFW"

project "Glad"
	location "Crown/vendor/Glad"
	kind "StaticLib"
	language "C"
	staticruntime "off"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	-- Generated by glad2: python -m glad --api gl:core=4.6 --extensions="" c
	files
	{
		"Crown/vendor/Glad/include/glad/gl.h",
		"Crown/vendor/Glad/include/KHR/khrplatform.h",
		"Crown/vendor/Glad/src/gl.c"
	}

	includedirs { "%{IncludeDir.Glad}" }

	filter "system:windows"
		systemversion "latest"

	filter "configurations:Debug"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release or Dist"
		runtime "Release"
		optimize "on"


project "ImGui"
	location "Crown/vendor/imgui"
	kind "StaticLib"
	language "C++"
	cppdialect "C++17"
	staticruntime "off"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	-- Core plus only the two backends this engine uses.
	files
	{
		"Crown/vendor/imgui/imgui.cpp",
		"Crown/vendor/imgui/imgui_draw.cpp",
		"Crown/vendor/imgui/imgui_tables.cpp",
		"Crown/vendor/imgui/imgui_widgets.cpp",
		"Crown/vendor/imgui/imgui_demo.cpp",
		"Crown/vendor/imgui/backends/imgui_impl_glfw.cpp",
		"Crown/vendor/imgui/backends/imgui_impl_opengl3.cpp"
	}

	includedirs
	{
		"%{IncludeDir.ImGui}",
		"%{IncludeDir.ImGui}/backends",
		"%{IncludeDir.GLFW}"
	}

	filter "system:windows"
		systemversion "latest"

	filter "configurations:Debug"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release or Dist"
		runtime "Release"
		optimize "on"

project "Crown"
	location "Crown"
	kind "StaticLib"
	language "C++"
	cppdialect "C++17"
	staticruntime "off"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	pchheader "crpch.h"
	pchsource "Crown/src/crpch.cpp"

	files
	{
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs
	{
		"%{prj.name}/src",
		"%{prj.name}/vendor/spdlog/include",
		"%{IncludeDir.GLFW}",
		"%{IncludeDir.Glad}",
		"%{IncludeDir.glm}",
		"%{IncludeDir.ImGui}",
		"%{IncludeDir.ImGui}/backends",
		"%{IncludeDir.stb}"
	}

	links
	{
		"GLFW",
		"Glad",
		"ImGui",
		"opengl32.lib"
	}

	filter "system:windows"
		systemversion "latest"
		buildoptions { "/utf-8" }
		defines
		{
			"CROWN_PLATFORM_WINDOWS",
			"GLFW_INCLUDE_NONE"
		}

	filter "configurations:Debug"
		defines "CROWN_DEBUG"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		defines "CROWN_RELEASE"
		runtime "Release"
		optimize "on"

	filter "configurations:Dist"
		defines "CROWN_DIST"
		runtime "Release"
		optimize "on"

project "Sandbox"
	location "Sandbox"
	kind "ConsoleApp"
	language "C++"
	cppdialect "C++17"
	staticruntime "off"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	files
	{
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs
	{
		"Crown/vendor/spdlog/include",
		"Crown/src",
		"%{IncludeDir.glm}",
		"%{IncludeDir.ImGui}"
	}

	links
	{
		"Crown",
		"ImGui"
	}

	filter "system:windows"
		systemversion "latest"
		buildoptions { "/utf-8" }
		defines
		{
			"CROWN_PLATFORM_WINDOWS"
		}

	filter "configurations:Debug"
		defines "CROWN_DEBUG"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		defines "CROWN_RELEASE"
		runtime "Release"
		optimize "on"

	filter "configurations:Dist"
		defines "CROWN_DIST"
		runtime "Release"
		optimize "on"
